name: Deploy project-web to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy project-web to gh-pages
      run: |
        mkdir -p out
        cp -r project-web/* out/
        cd out
        git init
        git remote add origin https://github.com/<your-username>/<your-repo>.git
        git checkout -b gh-pages
        git add .
        git commit -m "Deploy project-web to GitHub Pages"
        git push --force origin gh-pages
